const EventBus = {
    _listeners: {},     // collection of the events generated by the other modules

    on(event, callback) {
        if(!this._listeners[event]) this._listeners[event] = [] // if it doesn't exist, create the key [event] and then push the collback to that event
        this._listeners[event].push(callback)
    },

    emit(event, data) {
        if (!this._listeners[event]) return
        this._listeners[event].forEach(cb => cb(data))
    },

    off(event, callback) {
        if(!this._listeners[event]) return
        this._listeners[event] = this._listeners(cb => cb !== callback)
    }
}

export default EventBus